  #ifndef __AMDGPU_MDEV_COMMON_H__
  #define __AMDGPU_MDEV_COMMON_H__

typedef enum guest_request {
	AMDGPU_GUEST_CMD_OPEN_KMS,
	AMDGPU_GUEST_CMD_CLOSE_KMS,
	AMDGPU_GUEST_CMD_IOCTL_INFO,
	AMDGPU_GUEST_CMD_IOCTL_CTX,
	AMDGPU_GUEST_CMD_IOCTL_GEM_CREATE,
	AMDGPU_GUEST_CMD_IOCTL_VM,
	AMDGPU_GUEST_CMD_IOCTL_SCHED,
	AMDGPU_GUEST_CMD_IOCTL_BO_LIST,
	AMDGPU_GUEST_CMD_IOCTL_FENCE_TO_HANDLE,
	AMDGPU_GUEST_CMD_IOCTL_GEM_MMAP,
	AMDGPU_GUEST_CMD_IOCTL_GEM_WAIT_IDLE,
	AMDGPU_GUEST_CMD_IOCTL_CS,
	AMDGPU_GUEST_CMD_IOCTL_WAIT_CS,
	AMDGPU_GUEST_CMD_IOCTL_WAIT_FENCES,
	AMDGPU_GUEST_CMD_IOCTL_GEM_METADATA,
	AMDGPU_GUEST_CMD_IOCTL_GEM_VA,
	AMDGPU_GUEST_CMD_IOCTL_GEM_OP

} guest_request;

struct guest_ioctl {
	unsigned int cmd;
	bool ioctl_completed;
	void __user *ioctl_out_ptr;
	u32 size;
	u32 handle;
	pid_t id;
	u64 offset;
};

#endif
